/**
 * CodeGeneratorService
 *
 * Generates customized code files from a base template family by applying
 * a CustomizationConfig. This is the implementation of the Template Generator
 * component described in the design document.
 *
 * Property 16 (design.md): For any valid template and customization config,
 * the generated code MUST include:
 *   - All customization values in config files
 *   - Stellar network environment variables
 *   - Preserved Turborepo / monorepo structure
 *   - Syntactically valid TypeScript/JSON
 *   - stellar-sdk in package.json dependencies
 *
 * Validates: Requirements 7.1, 7.2, 7.3, 7.4, 7.5
 */

import type {
    CustomizationConfig,
    BrandingConfig,
    FeatureConfig,
    StellarConfig,
} from '@craft/types';
import type { GeneratedFile, GenerationResult, GenerationRequest } from '@craft/types';

// ── Network constants ─────────────────────────────────────────────────────────

export const NETWORK_PASSPHRASE: Record<'mainnet' | 'testnet', string> = {
    mainnet: 'Public Global Stellar Network ; September 2015',
    testnet: 'Test SDF Network ; September 2015',
};

export const DEFAULT_HORIZON_URL: Record<'mainnet' | 'testnet', string> = {
    mainnet: 'https://horizon.stellar.org',
    testnet: 'https://horizon-testnet.stellar.org',
};

// ── Template families ─────────────────────────────────────────────────────────

export type TemplateFamilyId =
    | 'stellar-dex'
    | 'soroban-defi'
    | 'payment-gateway'
    | 'asset-issuance';

// ── Generator ─────────────────────────────────────────────────────────────────

export class CodeGeneratorService {
    /**
     * Generate all files for a given template + customization.
     * Returns a GenerationResult with the full file tree.
     */
    generate(request: GenerationRequest & { templateFamily: TemplateFamilyId }): GenerationResult {
        const { templateFamily, customization } = request;

        try {
            const files: GeneratedFile[] = [
                this.generateConfigFile(templateFamily, customization),
                this.generateEnvFile(customization),
                this.generatePackageJson(templateFamily, customization),
                ...this.generateFamilySpecificFiles(templateFamily, customization),
            ];

            return { success: true, generatedFiles: files, errors: [] };
        } catch (err: any) {
            return {
                success: false,
                generatedFiles: [],
                errors: [{ file: 'unknown', message: err?.message ?? String(err), severity: 'error' }],
            };
        }
    }

    // ── Config file ───────────────────────────────────────────────────────────

    generateConfigFile(family: TemplateFamilyId, cfg: CustomizationConfig): GeneratedFile {
        const { branding, features, stellar } = cfg;
        const passphrase = NETWORK_PASSPHRASE[stellar.network];

        const sorobanLine = stellar.sorobanRpcUrl
            ? `        sorobanRpcUrl: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || '${stellar.sorobanRpcUrl}',\n`
            : family === 'soroban-defi'
            ? `        sorobanRpcUrl: process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org',\n`
            : '';

        const content = `// Auto-generated by CRAFT Platform
// Template: ${family}

export const config = {
    branding: {
        appName: process.env.NEXT_PUBLIC_APP_NAME || '${this.escapeStr(branding.appName)}',
        primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '${branding.primaryColor}',
        secondaryColor: process.env.NEXT_PUBLIC_SECONDARY_COLOR || '${branding.secondaryColor}',
        fontFamily: process.env.NEXT_PUBLIC_FONT_FAMILY || '${this.escapeStr(branding.fontFamily)}',
    },
    stellar: {
        network: process.env.NEXT_PUBLIC_STELLAR_NETWORK as 'mainnet' | 'testnet' || '${stellar.network}',
        horizonUrl: process.env.NEXT_PUBLIC_HORIZON_URL || '${stellar.horizonUrl}',
${sorobanLine}        networkPassphrase: process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || '${passphrase}',
    },
    features: {
        enableCharts: process.env.NEXT_PUBLIC_ENABLE_CHARTS === 'true' || ${features.enableCharts},
        enableTransactionHistory: process.env.NEXT_PUBLIC_ENABLE_TRANSACTION_HISTORY === 'true' || ${features.enableTransactionHistory},
        enableAnalytics: process.env.NEXT_PUBLIC_ENABLE_ANALYTICS === 'true' || ${features.enableAnalytics},
        enableNotifications: process.env.NEXT_PUBLIC_ENABLE_NOTIFICATIONS === 'true' || ${features.enableNotifications},
    },
} as const;

export default config;
`;

        return { path: 'src/lib/config.ts', content, type: 'config' };
    }

    // ── .env file ─────────────────────────────────────────────────────────────

    generateEnvFile(cfg: CustomizationConfig): GeneratedFile {
        const { branding, features, stellar } = cfg;
        const passphrase = NETWORK_PASSPHRASE[stellar.network];

        const lines: string[] = [
            '# Auto-generated by CRAFT Platform',
            `NEXT_PUBLIC_APP_NAME=${branding.appName}`,
            `NEXT_PUBLIC_PRIMARY_COLOR=${branding.primaryColor}`,
            `NEXT_PUBLIC_SECONDARY_COLOR=${branding.secondaryColor}`,
            `NEXT_PUBLIC_FONT_FAMILY=${branding.fontFamily}`,
            `NEXT_PUBLIC_STELLAR_NETWORK=${stellar.network}`,
            `NEXT_PUBLIC_HORIZON_URL=${stellar.horizonUrl}`,
            `NEXT_PUBLIC_NETWORK_PASSPHRASE=${passphrase}`,
            `NEXT_PUBLIC_ENABLE_CHARTS=${features.enableCharts}`,
            `NEXT_PUBLIC_ENABLE_TRANSACTION_HISTORY=${features.enableTransactionHistory}`,
            `NEXT_PUBLIC_ENABLE_ANALYTICS=${features.enableAnalytics}`,
            `NEXT_PUBLIC_ENABLE_NOTIFICATIONS=${features.enableNotifications}`,
        ];

        if (stellar.sorobanRpcUrl) {
            lines.push(`NEXT_PUBLIC_SOROBAN_RPC_URL=${stellar.sorobanRpcUrl}`);
        }

        return { path: '.env.local', content: lines.join('\n') + '\n', type: 'config' };
    }

    // ── package.json ──────────────────────────────────────────────────────────

    generatePackageJson(family: TemplateFamilyId, cfg: CustomizationConfig): GeneratedFile {
        const pkg: Record<string, any> = {
            name: `${family}-app`,
            version: '0.1.0',
            private: true,
            scripts: {
                dev: 'next dev',
                build: 'next build',
                start: 'next start',
                lint: 'next lint',
            },
            dependencies: {
                next: '14.0.4',
                react: '^18.2.0',
                'react-dom': '^18.2.0',
                'stellar-sdk': '^11.2.2',
            },
            devDependencies: {
                '@types/node': '^20.10.6',
                '@types/react': '^18.2.45',
                typescript: '^5.3.3',
            },
        };

        // Soroban templates need the Soroban client
        if (family === 'soroban-defi') {
            pkg.dependencies['@stellar/stellar-sdk'] = '^11.2.2';
        }

        return {
            path: 'package.json',
            content: JSON.stringify(pkg, null, 2) + '\n',
            type: 'config',
        };
    }

    // ── Family-specific files ─────────────────────────────────────────────────

    private generateFamilySpecificFiles(
        family: TemplateFamilyId,
        cfg: CustomizationConfig
    ): GeneratedFile[] {
        switch (family) {
            case 'stellar-dex':
                return this.generateDexFiles(cfg);
            case 'soroban-defi':
                return this.generateSorobanFiles(cfg);
            case 'payment-gateway':
                return this.generatePaymentFiles(cfg);
            case 'asset-issuance':
                return this.generateAssetIssuanceFiles(cfg);
        }
    }

    private generateDexFiles(cfg: CustomizationConfig): GeneratedFile[] {
        return [
            {
                path: 'src/lib/stellar.ts',
                content: this.stellarClientTemplate(cfg.stellar, false),
                type: 'code',
            },
        ];
    }

    private generateSorobanFiles(cfg: CustomizationConfig): GeneratedFile[] {
        return [
            {
                path: 'src/lib/stellar.ts',
                content: this.stellarClientTemplate(cfg.stellar, true),
                type: 'code',
            },
            {
                path: 'src/lib/soroban.ts',
                content: this.sorobanClientTemplate(cfg.stellar),
                type: 'code',
            },
        ];
    }

    private generatePaymentFiles(cfg: CustomizationConfig): GeneratedFile[] {
        return [
            {
                path: 'src/lib/stellar.ts',
                content: this.stellarClientTemplate(cfg.stellar, false),
                type: 'code',
            },
            {
                path: 'src/lib/payment.ts',
                content: this.paymentTemplate(cfg),
                type: 'code',
            },
        ];
    }

    private generateAssetIssuanceFiles(cfg: CustomizationConfig): GeneratedFile[] {
        return [
            {
                path: 'src/lib/stellar.ts',
                content: this.stellarClientTemplate(cfg.stellar, false),
                type: 'code',
            },
            {
                path: 'src/lib/asset.ts',
                content: this.assetIssuanceTemplate(cfg),
                type: 'code',
            },
        ];
    }

    // ── Code templates ────────────────────────────────────────────────────────

    private stellarClientTemplate(stellar: StellarConfig, includeSoroban: boolean): string {
        const sorobanImport = includeSoroban
            ? `import { SorobanRpc } from 'stellar-sdk';\n`
            : '';
        const sorobanExport = includeSoroban
            ? `\nexport const sorobanServer = new SorobanRpc.Server(config.stellar.sorobanRpcUrl!);\n`
            : '';

        return `// Auto-generated by CRAFT Platform
import * as StellarSdk from 'stellar-sdk';
${sorobanImport}import { config } from './config';

export const server = new StellarSdk.Server(config.stellar.horizonUrl);
export const networkPassphrase = config.stellar.networkPassphrase;
${sorobanExport}
export async function loadAccount(publicKey: string) {
    try {
        return await server.loadAccount(publicKey);
    } catch (error) {
        throw new Error(\`Failed to load account: \${error}\`);
    }
}

export async function getAccountBalance(publicKey: string) {
    const account = await loadAccount(publicKey);
    return account.balances;
}

export async function submitTransaction(transaction: StellarSdk.Transaction) {
    try {
        return await server.submitTransaction(transaction);
    } catch (error) {
        throw new Error(\`Failed to submit transaction: \${error}\`);
    }
}
`;
    }

    private sorobanClientTemplate(stellar: StellarConfig): string {
        return `// Auto-generated by CRAFT Platform — Soroban RPC client
import { SorobanRpc, Contract } from 'stellar-sdk';
import { config } from './config';

export const sorobanServer = new SorobanRpc.Server(
    config.stellar.sorobanRpcUrl!
);

export async function invokeContract(
    contractId: string,
    method: string,
    args: any[]
): Promise<any> {
    try {
        const contract = new Contract(contractId);
        const tx = contract.call(method, ...args);
        return await sorobanServer.simulateTransaction(tx as any);
    } catch (error) {
        throw new Error(\`Contract invocation failed: \${error}\`);
    }
}
`;
    }

    private paymentTemplate(cfg: CustomizationConfig): string {
        return `// Auto-generated by CRAFT Platform — Payment Gateway
import * as StellarSdk from 'stellar-sdk';
import { server, networkPassphrase } from './stellar';

export interface PaymentRequest {
    destination: string;
    amount: string;
    asset: StellarSdk.Asset;
    memo?: string;
}

export async function sendPayment(
    sourceKeypair: StellarSdk.Keypair,
    request: PaymentRequest
): Promise<StellarSdk.Horizon.HorizonApi.SubmitTransactionResponse> {
    const account = await server.loadAccount(sourceKeypair.publicKey());
    const tx = new StellarSdk.TransactionBuilder(account, {
        fee: StellarSdk.BASE_FEE,
        networkPassphrase,
    })
        .addOperation(
            StellarSdk.Operation.payment({
                destination: request.destination,
                asset: request.asset,
                amount: request.amount,
            })
        )
        .setTimeout(30)
        .build();

    tx.sign(sourceKeypair);
    return server.submitTransaction(tx);
}
`;
    }

    private assetIssuanceTemplate(cfg: CustomizationConfig): string {
        return `// Auto-generated by CRAFT Platform — Asset Issuance
import * as StellarSdk from 'stellar-sdk';
import { server, networkPassphrase } from './stellar';

export async function issueAsset(
    issuerKeypair: StellarSdk.Keypair,
    assetCode: string,
    distributorPublicKey: string,
    amount: string
): Promise<StellarSdk.Horizon.HorizonApi.SubmitTransactionResponse> {
    const asset = new StellarSdk.Asset(assetCode, issuerKeypair.publicKey());
    const account = await server.loadAccount(issuerKeypair.publicKey());

    const tx = new StellarSdk.TransactionBuilder(account, {
        fee: StellarSdk.BASE_FEE,
        networkPassphrase,
    })
        .addOperation(
            StellarSdk.Operation.payment({
                destination: distributorPublicKey,
                asset,
                amount,
            })
        )
        .setTimeout(30)
        .build();

    tx.sign(issuerKeypair);
    return server.submitTransaction(tx);
}
`;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private escapeStr(s: string): string {
        return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    }
}

export const codeGeneratorService = new CodeGeneratorService();
